<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>21daca77-f5a0-4bfb-ab62-9d6aa9fa10fa</testSuiteGuid>
   <testCaseLink>
      <guid>24deaa88-2b0a-445d-94eb-fc47569b00b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/excel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4e937b78-f9fe-430f-9684-13417e4d1d4f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Test Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4e937b78-f9fe-430f-9684-13417e4d1d4f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>fc25d8d8-beaf-4adf-aec4-28c0bdfa7b29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4e937b78-f9fe-430f-9684-13417e4d1d4f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>4d974fe9-bfd1-44a8-89aa-6c7461cd7e05</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
